import {get} from 'react-native/Libraries/TurboModule/TurboModuleRegistry';

export const LOCALIZED_STRINGS = {
  en: {
    'Welcome to HDiDA!': 'Welcome to HDiDA!',
    "HDIDA is the first automotive social marketplace in Algeria, designed for buyer, and seller together in one dynamic platform. Whether you're looking to buy, sell, or just connect with other automotive lovers, HDIDA has it all.":
      "HDIDA is the first automotive social marketplace in Algeria, designed for buyer, and seller together in one dynamic platform. Whether you're looking to buy, sell, or just connect with other automotive lovers, HDIDA has it all.",
    'Offers Near You': 'Offers Near You',
    Notifications: 'Notifications',
    'Old Password': 'Old Password',
    'New Password': 'New Password',
    'Confirm New Password': 'Confirm New Password',
    'Change Password': 'Change Password',
    select_language: 'Select Language',
    you_can_always_change_your_language_in_settings:
      'You can always change your language in settings',
    english: 'English',
    arabic: 'Arabic',
    continue: 'Continue',
    welcome_to: 'Welcome to',
    HDIDA: 'HDIDA',
    the_best_car_marketplace_app_of_the_century_for_your_transportation_needs:
      'The best car marketplace app of the century for your transportation needs',
    sign_in_to_continue: 'Sign in to continue',
    phone_number: 'Phone Number',
    by_proceding:
      'By proceeding, you consent to receive calls, Whatsapp or SMS messages, including by automated means, from uber and its affiliates to the number provided.',
    sign_in_as_guest: 'Sign in as guest',
    continue_with_google: 'Continue with Google',
    continue_with_facebook: 'Continue with Facebook',
    continue_with_apple: 'Continue with Apple',
    next: 'Next',
    or: 'or',
    enter_verification_code: 'Enter verification code',
    enter_the_code_Sent_to: 'Enter the code Sent to',
    i_have_not_received_the_code: 'I have not received the code',
    login_with_password: 'Login with password',
    create_new_password: 'Create new password',
    password: 'Password',
    confirm_password: 'Confirm Password',
    congratulations: 'Congratulations',
    yout_account_is_successfully_created:
      'Your account is successfully created.You can now sell and buy',
    search: 'Search',
    filters: 'Filters',
    promoted_offers: 'Promoted Offers',
    see_all: 'See all',
    browse_categories: 'Browse Categories',
    near_you: 'Near You',
    just_for_you: 'Just For You',
    like: 'Like',
    comment: 'Comment',
    share: 'Share',
    edit: 'Edit',
    delete: 'Delete',
    contact: 'Contact',
    home: 'Home',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    sell: 'Sell',
    ads: 'Ads',
    chat: 'Chat',
    preferences: 'Preferences',
    see_offers_on_map: 'See Offers on Map',
    apply_filters: 'Apply Filters',
    categories: 'Categories',
    useful_links: 'Useful Links',
    privacy_policy_and_terms: 'Privacy Policy and Terms',
    help_and_support: 'Help & Support',
    refer_a_friend: 'Refer a Friend',
    about_us: 'About Us',
    vehicle_type: 'Vehicle Type',
    car_truck_motorcycle_boat: 'Car/Truck, motorcycle, boat, etc',
    make: 'Make',
    ford_audi_honda_chevy: 'Ford, Audi, Honda, Chevrolet, etc',
    body_style: 'Body Style',
    sedan_convertible_truck: 'Sedan, convertible, truck, etc',
    price: 'Price',
    select_budget: 'Select your budget range',
    reset: 'Reset',
    car_info: 'Car Info',
    car_features: 'Car Features',
    about_seller: 'About Seller',
    member_since: 'Member since',
    see_profile: 'See Profile',
    description: 'Description',
    suggestions: 'Suggestions',
    sms: 'SMS',
    call: 'Call',
    chat_now: 'Chat Now',
    followers: 'Followers',
    following: 'Following',
    message: 'Message',
    follow: 'Follow',
    messages: 'Messages',
    home: 'Home',
    ads: 'Ads',
    sell: 'Sell',
    chat: 'Chat',
    profile: 'Profile',
    no_ads_found: 'No Ads Found',
    hope_you_can_get_some_soon: `Hope you can get some soon!`,
    just_for_you: 'Just for you',
    near_you: 'Near you',
    promoted_offers: 'Promoted Offers',
    search: 'Search',
    filter: 'Filter',
    my_profile: 'My Profile',
    buy_packagees_and_my_orders: 'Buy Packages and My Orders',
    packages_orders_and_billing_history: 'Packages, Orders and Billing History',
    my_favorites: 'My Favorites',
    results: 'Resuts',
    edit_profile: 'Edit Profile',
    language: 'Language',
    change_language: 'Change Language',
    select_lang: 'Select Language',
    select_language_text: 'You can always change your language in settings',
    best_app_message: ` The best car marketplace app of the century for your transportation needs!`,
    welcome_to: 'Welcome to',
    sign_in_message: `By proceeding, you consent to get calls, Whatsapp or SMS messages,including by automated means, from uber and its affiliates to the number provided.`,
    error: 'Error',
    enter_otp_message: 'Please enter a valid OTP',
    enter_the_verification_code: 'Please enter the verification code',
    enter_code_Sent_to: 'Enter code Sent to',
    posted_on: 'Posted on',
    ad_will_expire_in: 'Ad will expire in',
    days: 'Days',
    active: 'Active',
    removed: 'Removed',
    my_ads: 'My Ads',
    ad_title: 'Ad Title',
    enter_title: 'Enter Title',
    upload_image: 'Upload Image',
    recommended_size: 'Recommended Size: 3:1',
    enter_description: 'Enter Description',
    take_phone: 'Take Photo',
    sell_car: 'Sell Car',
    ad_price: 'Ad Price',
    enter_price: 'Enter Price',
    firm_on_price: 'Firm on price',
    use_credit: 'Use Credit',
    promote_your_ad: 'Promote Your Ad',
    skip: 'Skip',
    sell_10x_faster: 'Sell 10x Faster',
    boost_your_ad_to_top_listings: 'Boost Your Ad to top Listings',
    get_noticed_with_a_promoted_tag: 'Get Noticed with a Promoted Tag',
    add_image_of_car: 'Add Image of Car',
    take_photo: 'Take Photo',
    unfollow: 'Unfollow',
    save: 'Save',
    address: 'Address',
    darkMode: 'Dark Mode',
    buy_packages: 'Buy Packages',
    select_address: 'Select Address',
    get_verified: 'Get Verified',
    get_verified_text: `Apply as Vendor and Get more trust in your profile ,badge on your
    profile, and get noticed immediately`,
    get_veification_badge: 'Get Verified Badge',
    top_questions: 'Top Questions',
    FAQ: 'FAQ',
    'Contact Us': 'Contact Us',
    'Car Info': 'Car Info',
    'Car Features': 'Car Features',
    Description: 'Description',
    'See Profile': 'See Profile',
    'About Seller': 'About Seller',
    SMS: 'SMS',
    Phone: 'Phone',
    'Chat Now': 'Chat Now',
    Edit: 'Edit',
    Save: 'Save',
    'Add New Address': 'Add New Address',
    'Address Details': 'Address Details',
    'Promote Ad - 10x faster': 'Promote Ad - 10x faster',
    'Delete this Post': 'Delete this Post',
    'Are you sure you want to delete this post?':
      'Are you sure you want to delete this post?',
    Yes: 'Yes',
    Cancel: 'Cancel',
    'Be the first to comment!': 'Be the first to comment!',
    'No Comments': 'No Comments',
    comments: 'Comments',
    'No notifications found': 'No notifications found',
  },
  ar: {
    'Welcome to HDiDA!': 'مرحبا بكم في حديدة!',
    "HDIDA is the first automotive social marketplace in Algeria, designed for buyer, and seller together in one dynamic platform. Whether you're looking to buy, sell, or just connect with other automotive lovers, HDIDA has it all.":
      'حديده هو أول سوق اجتماعي للسيارات في الجزائر، مصمم للمشترين والبائعين معًا على منصة ديناميكية واحدة. سواء كنت تبحث عن شراء أو بيع أو مجرد التواصل مع محبي السيارات الآخرين، فإن حديدة يوفر لك كل ما تحتاجه.',
    'Offers Near You': 'العروض القريبة منك',
    Notifications: 'الاشعارات',
    'Change Password': 'تغيير كلمة المرور',
    'Old Password': 'كلمة المرور القديمة',
    'New Password': 'كلمة المرور الجديدة',
    'Confirm Password': 'تأكيد كلمة المرور',
    select_language: 'اختر اللغة',
    you_can_always_change_your_language_in_settings:
      'يمكنك تغيير اللغة في الإعدادات',
    english: 'الإنجليزية',
    arabic: 'العربية',
    continue: 'متابعة',
    welcome_to_HDIDA: 'مرحبا بك في',
    HDIDA: 'الحديدة',
    the_best_car_marketplace_app_of_the_century_for_your_transportation_needs:
      'أفضل تطبيق لسوق السيارات في القرن لتلبية احتياجات النقل الخاصة بك',
    sign_in_to_continue: 'تسجيل الدخول للمتابعة',
    phone_number: 'رقم الهاتف',
    by_proceding:
      'من خلال المتابعة، فإنك توافق على تلقي المكالمات أو رسائل Whatsapp أو الرسائل النصية القصيرة، بما في ذلك الوسائل الآلية، من شركة uber والشركات التابعة لها على الرقم المقدم.',
    sign_in_as_guest: 'تسجيل الدخول ك ك غير مستخدم',
    continue_with_google: 'متابعة مع Google',
    continue_with_facebook: 'متابعة مع Facebook',
    continue_with_apple: 'متابعة مع Apple',
    next: 'التالي',
    or: 'أو',
    enter_verification_code: 'اكتب رمز التحقق',
    enter_the_code_Sent_to: 'اكتب رمز التحقق',
    i_have_not_received_the_code: 'لم يتلق رمز التحقق',
    login_with_password: 'تسجيل الدخول بكلمة مرور',
    create_new_password: 'إنشاء ك كلمة مرور جديدة',
    password: 'كلمة مرور',
    confirm_password: 'تاكيد ك كلمة مرور',
    congratulations: 'تهانينا',
    yout_account_is_successfully_created:
      'تم إنشاء حسابك بنجاح. يمكنك البيع والشراء',
    search: 'بحث',
    filters: 'فلترات',
    promoted_offers: 'عروض مميزة',
    see_all: 'اظهار الكل',
    browse_categories: 'تصفح الفئات',
    near_you: 'حاليا فقط',
    just_for_you: 'فقط لك',
    like: 'اعجب',
    comment: 'تعليق',
    share: 'شارك',
    edit: 'تعديل',
    delete: 'حذف',
    contact: 'تواصل',
    home: 'الرئيسية',
    profile: 'الملف الشخصي',
    settings: 'إعدادات',
    logout: 'تسجيل الخروج',
    sell: 'بيع',
    ads: 'الاعلانات',
    chat: 'المحادثة',
    preferences: 'إعدادات',
    see_offers_on_map: 'اظهار العروض على الخريطة',
    apply_filters: 'تطبيق فلترات',
    categories: 'الفئات',
    useful_links: 'روابط مفيدة',
    privacy_policy_and_terms: 'سياسة الخصوصية والشروط',
    help_and_support: 'المساعدة والدعم',
    refer_a_friend: 'شارك أصدقائك',
    about_us: 'معلومات عنا',
    vehicle_types: 'نوع السيارة',
    car_truck_motorcycle_boat: 'سيارة، شاحنة، دراجة نارية، قارب، الخ',
    make: 'Make',
    ford_audi_honda_chevy: 'فورد، أودي، هوندا، شيفروليه، الخ',
    body_style: 'نمط الجسم',
    sedan_convertible_truck: 'سيدان، قابلة للتحويل، شاحنة، الخ',
    price: 'ثمن',
    select_budget: 'حدد نطاق ميزانيتك',
    reset: 'إعادة تعيين',
    car_info: 'معلومات السيارة',
    car_features: 'خصائص السيارة',
    about_seller: 'معلومات البائع',
    member_since: 'عضو منذ',
    see_profile: 'عرض الصفحة الشخصية',
    description: 'الوصف',
    suggestions: 'اقتراحات',
    sms: 'SMS',
    call: 'اتصال',
    chat_now: 'التواصل الآن',
    followers: 'متابعون',
    following: 'متابعين',
    follow: 'تابع',
    message: 'رسالة',
    home: 'الرئيسية',
    ads: 'الاعلانات',
    sell: 'بيع',
    chat: 'المحادثة',
    profile: 'الشخصي',
    no_ads_found: 'لا يوجد اعلانات',
    hope_you_can_get_some_soon: 'مرحبا بكم في موقعنا في وقت لاحق',
    just_for_you: 'فقط لك',
    near_you: 'حاليا فقط',
    promoted_offers: 'عروض مميزة',
    search: `بحث`,
    filter: 'فلترات',
    my_profile: 'ملفي',
    buy_packagees_and_my_orders: 'شراء الباقات وطلباتي',
    packages_orders_and_billing_history: 'الباقات وطلباتي وسجل الفواتير',
    my_favorites: 'مفضلاتي',
    result: 'النتيجة',
    edit_profile: 'تعديل الملف الشخصي',
    address: 'العنوان',
    language: 'اللغة',
    change_language: 'تغيير اللغة',
    select_lang: 'اختر اللغة',
    select_language_text: 'يمكنك تغيير اللغة في صفحة الاعدادات',
    best_app_message: 'أفضل تطبيق للبحث عن السيارات القديمة في القطر السوري',
    welcome_to: 'مرحبا بك في',
    sign_in_message: `بالمتابعة، فإنك توافق على تلقي مكالمات أو رسائل واتس اب أو رسائل نصية قصيرة،
        بما في ذلك الوسائل الآلية، بدءًا من شركة أوبر والشركات التابعة لها وحتى
        الرقم المقدم.`,
    error: 'خطأ',
    my_ads: 'اعلاناتي',
    posted_on: 'نشر في',
    ad_will_expire_in: 'ستنتهي الإعلان في خلال',
    days: 'أيام',
    active: 'نشط',
    removed: 'تمت الإزالة',
    ad_title: 'عنوان الإعلان',
    enter_title: 'أدخل العنوان',
    upload_image: 'تحميل الصورة',
    recommended_size: 'الحجم الموصى به: 3:1',
    enter_description: 'أدخل الوصف',
    take_photo: 'التقاط صورة',
    sell_car: 'بيع السيارة',
    ad_price: 'سعر الإعلان',
    enter_price: 'أدخل السعر',
    firm_on_price: 'ثابت السعر',
    use_credit: 'استخدام الائتمان',
    promote_your_ad: 'تعزيز إعلانك',
    skip: 'تخطى',
    sell_10x_faster: 'بيع بسرعة 10 مرات أكثر',
    boost_your_ad_to_top_listings: 'قم بتعزيز إعلانك للقوائم الرئيسية',
    get_noticed_with_a_promoted_tag: 'لاحظ بوسم معزز',
    add_image_of_car: 'اضف صورة السيارة',
    take_phote: 'التقاط صورة',
    description: 'وصف',
    unfollow: 'الغاء المتابعة',
    save: 'حفظ',
    darkMode: 'الوضع الداكن',
    buy_packages: 'شراء الباقات',
    select_address: 'حدد العنوان',
    get_verified: `حصلت على التحقق`,
    get_verified_text: `تقدم بطلبك كبائع واحصل على المزيد من الثقة في ملفك الشخصي والشارة الموجودة على حسابك
    الملف الشخصي، ولاحظ على الفور`,
    get_veification_badge: 'احصل على شارة التحقق',
    top_questions: 'أسئلة شائعة',
    'No notifications found': 'لم يتم العثور على أي إشعارات',
    FAQ: 'الأسئلة الشائعة',
    'Contact Us': 'اتصل بنا',
    'Car Info': 'معلومات السيارة',
    'Car Features': 'ميزات السيارة',
    Description: 'الوصف',
    'See Profile': 'عرض الملف الشخصي',
    'About Seller': 'حول البائع',
    SMS: 'رسالة نصية',
    Phone: 'هاتف',
    'Chat Now': 'الدردشة الآن',
    Edit: 'تعديل',
    Save: 'حفظ',
    'Add New Address': 'اضف عنوان جديد',
    'Address Details': 'تفاصيل العنوان',
    'Promote Ad - 10x faster': 'تعزيز أعلان - 10x سرعة',
    'Delete this Post': 'حذف هذا الإعلان',
    'Are you sure you want to delete this post?':
      'هل انت متاكد من حذف هذا الإعلان؟',
    Yes: 'نعم',
    Cancel: 'الغاء',
    'Be the first to comment!': 'ابق على الاول للتعليق!',
    'No Comments': 'لا تعليقات',
    comments: 'تعليقات',
  },
  fr: {
    'Welcome to HDIDA!': 'Bienvenue sur HDiDA!',
    "HDIDA is the first automotive social marketplace in Algeria, designed for buyer, and seller together in one dynamic platform. Whether you're looking to buy, sell, or just connect with other automotive lovers, HDIDA has it all.":
      "HDIDA est le premier marché social automobile en Algérie, conçu pour l'acheteur et le vendeur réunis sur une seule plateforme dynamique. Que vous cherchiez à acheter, vendre ou simplement vous connecter avec d'autres amateurs d'automobile, HDIDA a tout pour plaire.",
    'Offers Near You': 'Offres proches de vous',
    Notifications: 'Notifications',
    'Change Password': 'Changer le mot de passe',
    'Old Password': 'Ancien mot de passe',
    'New Password': 'Nouveau mot de passe',
    'Confirm Password': 'Confirmer le mot de passe',
    'No notifications found': 'Aucune notification n’a été trouvé',
    select_language: 'Sélectionner la langue',
    you_can_always_change_your_language_in_settings:
      'Vous pouvez toujours changer votre langue dans les paramètres',
    english: 'Anglais',
    arabic: 'Arabe',
    continue: 'Continuer',
    welcome_to: 'Bienvenue à',
    HDIDA: 'HDIDA',
    the_best_car_marketplace_app_of_the_century_for_your_transportation_needs:
      'La meilleure application de marché de voitures du siècle pour vos besoins de transport',
    sign_in_to_continue: 'Connectez-vous pour continuer',
    phone_number: 'Numéro de téléphone',
    by_proceding:
      "En procédant, vous consentez à recevoir des appels, des messages Whatsapp ou SMS, y compris par des moyens automatisés, de la part d'Uber et de ses filiales au numéro fourni.",
    sign_in_as_guest: "Se connecter en tant qu'invité",
    continue_with_google: 'Continuer avec Google',
    continue_with_facebook: 'Continuer avec Facebook',
    continue_with_apple: 'Continuer avec Apple',
    next: 'Suivant',
    or: 'ou',
    enter_verification_code: 'Entrez le code de vérification',
    enter_the_code_Sent_to: 'Entrez le code envoyé à',
    i_have_not_received_the_code: "Je n'ai pas reçu le code",
    login_with_password: 'Se connecter avec le mot de passe',
    create_new_password: 'Créer un nouveau mot de passe',
    password: 'Mot de passe',
    confirm_password: 'Confirmer le mot de passe',
    congratulations: 'Félicitations',
    yout_account_is_successfully_created:
      'Votre compte est créé avec succès. Vous pouvez maintenant vendre et acheter',
    search: 'Rechercher',
    filters: 'Filtres',
    promoted_offers: 'Offres promues',
    see_all: 'Voir tout',
    browse_categories: 'Parcourir les catégories',
    near_you: 'Près de chez vous',
    just_for_you: 'Juste pour vous',
    like: "J'aime",
    comment: 'Commenter',
    share: 'Partager',
    edit: 'Modifier',
    delete: 'Supprimer',
    contact: 'Contacter',
    home: 'Accueil',
    profile: 'Profil',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    sell: 'Vendre',
    ads: 'Annonces',
    chat: 'Chat',
    preferences: 'Préférences',
    see_offers_on_map: 'Voir les offres sur la carte',
    apply_filters: 'Appliquer les filtres',
    categories: 'Catégories',
    useful_links: 'Liens utiles',
    privacy_policy_and_terms: 'Politique de confidentialité et conditions',
    help_and_support: 'Aide et assistance',
    refer_a_friend: 'Référez un ami',
    about_us: 'À propos de nous',
    vehicle_type: 'Type de véhicule',
    car_truck_motorcycle_boat: 'Voiture/Camion, moto, bateau, etc',
    make: 'Marque',
    ford_audi_honda_chevy: 'Ford, Audi, Honda, Chevrolet, etc',
    body_style: 'Style de carrosserie',
    sedan_convertible_truck: 'Berline, décapotable, camion, etc',
    price: 'Prix',
    select_budget: 'Sélectionnez votre fourchette de budget',
    reset: 'Réinitialiser',
    car_info: 'Informations sur la voiture',
    car_features: 'Caractéristiques de la voiture',
    about_seller: 'À propos du vendeur',
    member_since: 'Membre depuis',
    see_profile: 'Voir le profil',
    description: 'Description',
    suggestions: 'Suggestions',
    sms: 'SMS',
    call: 'Appeler',
    chat_now: 'Chat maintenant',
    followers: 'Abonnés',
    following: 'Abonnements',
    message: 'Message',
    follow: 'Suivre',
    messages: 'Messages',
    home: 'Accueil',
    ads: 'Annonces',
    sell: 'Vendre',
    chat: 'Chat',
    profile: 'Profil',
    no_ads_found: 'Aucune annonce trouvée',
    hope_you_can_get_some_soon:
      'Espérons que vous puissiez en obtenir bientôt !',
    just_for_you: 'Juste pour vous',
    near_you: 'Près de chez vous',
    promoted_offers: 'Offres promues',
    search: 'Recherche',
    filter: 'Filtre',
    my_profile: 'Mon profil',
    buy_packagees_and_my_orders: 'Acheter des forfaits et mes commandes',
    packages_orders_and_billing_history:
      'Forfaits, commandes et historique de facturation',
    my_favorites: 'Mes favoris',
    result: 'Resultat',
    edit_profile: 'Modifier le profil',
    address: 'Adresse',
    language: 'Langue',
    change_language: 'Changer la langue',
    select_lang: 'Sélectionner la langue',
    select_language_text:
      'Vous pouvez toujours changer votre langue dans les paramètres',
    best_app_message:
      'La meilleure application de recherche de voitures pour vos besoins de transport !',
    sign_in_message: `En continuant, vous acceptez les mises en garde de la politique et de l'application.`,
    error: 'Erreur',
    posted_on: 'Posté le',
    ad_will_expire_in: "L'annonce expirera dans",
    days: 'Jours',
    active: 'Actif',
    removed: 'Supprimé',
    my_ads: 'mes annonces',
    ad_title: "Titre de l'annonce",
    enter_title: 'Entrer le titre',
    upload_image: 'Télécharger une image',
    recommended_size: 'Taille recommandée : 3:1',
    enter_description: 'Entrer une description',
    take_photo: 'Prendre une photo',
    sell_car: 'Vendre la voiture',
    ad_price: "Prix de l'annonce",
    enter_price: 'Entrer le prix',
    firm_on_price: 'Ferme sur le prix',
    use_credit: 'Utiliser le crédit',
    promote_your_ad: 'Promouvoir votre annonce',
    skip: 'Passer',
    sell_10x_faster: 'Vendre 10 fois plus vite',
    boost_your_ad_to_top_listings:
      'Boostez votre annonce vers les premières annonces',
    get_noticed_with_a_promoted_tag:
      'Faites-vous remarquer avec une étiquette Promu',
    add_image_of_car: 'Add Image of Car',
    unfollow: 'Ne plus suivre',
    save: 'Enregistrer',
    darkMode: `Mode sombre`,
    buy_packages: 'Acheter des forfaits',
    select_address: 'Sélectionner une adresse',
    get_verified: 'Obtenir une certification',
    get_veification_badge: `احصل على شارة التحققObtenez un badge vérifié`,
    get_verified_text: `Postulez en tant que fournisseur et obtenez plus de confiance dans votre profil, badge sur votre
    profil et faites-vous remarquer immédiatement`,
    top_questions: `Questions les plus fréquentes`,
    FAQ: 'FAQ',
    'Contact Us': 'Contactez-nous',
    'Car Info': 'Infos Voiture',
    'Car Features': 'Caractéristiques de la voiture',
    Description: 'Description',
    'See Profile': 'Voir le profil',
    'About Seller': 'À propos du vendeur',
    SMS: 'SMS',
    Phone: 'Téléphone',
    'Chat Now': 'Discuter maintenant',
    Edit: 'Modifier',
    Save: 'Enregistrer',
    'Add New Address': 'Ajouter une nouvelle adresse',
    'Address Details': "Details de l'adresse",
    'Promote Ad - 10x faster': "Promouvoir l'annonce - 10x plus rapide",
    'Are you sure you want to delete this post?':
      'Etes-vous sur de vouloir supprimer cet article ?',
    Cancel: 'Annuler',
    'Be the first to comment!': 'Faites le premier à commenter!',
    'No Comments': 'Aucun commentaire',
    comments: 'Commentaires',
  },
};

export const localized = LOCALIZED_STRINGS.ar;
localized;
